#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xprop
Version  : 1.2.3
Release  : 1
URL      : https://www.x.org/releases/individual/app/xprop-1.2.3.tar.bz2
Source0  : https://www.x.org/releases/individual/app/xprop-1.2.3.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: xprop-bin
Requires: xprop-license
Requires: xprop-man
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
xprop is a command line tool to display and/or set window and font
properties of an X server.

%package bin
Summary: bin components for the xprop package.
Group: Binaries
Requires: xprop-license
Requires: xprop-man

%description bin
bin components for the xprop package.


%package license
Summary: license components for the xprop package.
Group: Default

%description license
license components for the xprop package.


%package man
Summary: man components for the xprop package.
Group: Default

%description man
man components for the xprop package.


%prep
%setup -q -n xprop-1.2.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1531977482
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1531977482
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/xprop
cp COPYING %{buildroot}/usr/share/doc/xprop/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xprop

%files license
%defattr(-,root,root,-)
/usr/share/doc/xprop/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/xprop.1
