#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : xprop
Version  : 1.2.6
Release  : 7
URL      : https://www.x.org/releases/individual/app/xprop-1.2.6.tar.xz
Source0  : https://www.x.org/releases/individual/app/xprop-1.2.6.tar.xz
Source1  : https://www.x.org/releases/individual/app/xprop-1.2.6.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: xprop-bin = %{version}-%{release}
Requires: xprop-license = %{version}-%{release}
Requires: xprop-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
= xprop
xprop is a command line tool to display and/or set window and font
properties of an X server.

%package bin
Summary: bin components for the xprop package.
Group: Binaries
Requires: xprop-license = %{version}-%{release}

%description bin
bin components for the xprop package.


%package license
Summary: license components for the xprop package.
Group: Default

%description license
license components for the xprop package.


%package man
Summary: man components for the xprop package.
Group: Default

%description man
man components for the xprop package.


%prep
%setup -q -n xprop-1.2.6
cd %{_builddir}/xprop-1.2.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1670223837
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1670223837
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xprop
cp %{_builddir}/xprop-%{version}/COPYING %{buildroot}/usr/share/package-licenses/xprop/2b0764374e20cde0bd7db31431c3609d14b32d3f
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xprop

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xprop/2b0764374e20cde0bd7db31431c3609d14b32d3f

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xprop.1
