#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : xprop
Version  : 1.2.4
Release  : 3
URL      : https://www.x.org/releases/individual/app/xprop-1.2.4.tar.bz2
Source0  : https://www.x.org/releases/individual/app/xprop-1.2.4.tar.bz2
Source99 : https://www.x.org/releases/individual/app/xprop-1.2.4.tar.bz2.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: xprop-bin = %{version}-%{release}
Requires: xprop-license = %{version}-%{release}
Requires: xprop-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
xprop is a command line tool to display and/or set window and font
properties of an X server.

%package bin
Summary: bin components for the xprop package.
Group: Binaries
Requires: xprop-license = %{version}-%{release}

%description bin
bin components for the xprop package.


%package license
Summary: license components for the xprop package.
Group: Default

%description license
license components for the xprop package.


%package man
Summary: man components for the xprop package.
Group: Default

%description man
man components for the xprop package.


%prep
%setup -q -n xprop-1.2.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557106469
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557106469
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xprop
cp COPYING %{buildroot}/usr/share/package-licenses/xprop/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xprop

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xprop/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xprop.1
